### ISSUE TITLE
Plotting lattice data

### ISSUE THREAD

**Issue by rainswor** [hibtc/pytao#1]
I’m trying to understand a little more about using tao and pytao.

Looking at examples it seems very common to do something with the following

```
for curve in tao.curve_names('beta'):
    x, y = tao.curve_data(curve).T
    plt.plot(x, y, label=curve)
```

I tried this with the recycler lattice which I took from the tao examples that came with the bmad install. However i get the following error

```
[ERROR | 2017-JUN-07 13:23:46] tao_python_cmd:
    "python -noprint plot_line beta.g.b": No line associated with curve
```

From this I have a few questions:

1. How do I know what curves I can use i.e. here I use ‘beta’ but is there a function I can call to tell me what curves I have? Do I use tao.plots() to get a list of available options? I also see tao.valid_graphs(). I wonder if i am confusing curves, plots and graphs.

2. Why is this case is there no line associated with the curve? How do I determine which curves have data?

**Comment by rainswor** [comment]
Response by @DavidSagan:

To get a list of possible plot use the command tao python command: `python plot_list t`.

To get a list of "displayed" plots where tao has calculated plotting curves use the command `python plot_list r`.

From the `python plot_list r` command you get a list of plot regions like:

```
1;layout;lat_layout;T
2;r11;;F
3;r12;;F
4;r22;;F
5;r13;beta;T
```

The T/F  (or lack of a plot name) tells you which regions have plots. For a region with a plot, to find the associated graphs use, for example:

```
Tao> python plot1 r13 
num_graphs;INT;T;1
graph[1];STR;T;g
name;STR;T;beta
…
```

This gives you a list of graphs (one, named “g" in this case). Then to see the curves associated with a graph use:	

```
Tao> python plot_graph r13.g
num_curves;INT;T;2
curve[1];STR;T;a
curve[2];STR;T;b
name;STR;T;g
…
```

> 2.) Why is this case is there no line associated with the curve? How do I determine which curves have data?


Finally to see the if a (curved) line and/or symbols are plotted use:

```
python plot_curve r13.g.b
name;STR;T;b
data_source;STR;T;lat
...
draw_line;LOGIC;T;T
draw_symbols;LOGIC;T;F
…
```

The draw_line and draw_symbols parameters tell you if a line and/or symbols are drawn.

drawing of lines or symbols is controlled by the user.

**Comment by rainswor** [comment]
Response by @coldfix:

For now, you should only be using lower level methods to execute tao
primitive commands or tao python commands David mentioned.

The most useful methods are:

### `Tao.command`

directly execute a tao command, you get no result, e.g.

```
tao.command("set element bb k1 = 1")
```

### `Tao.python`

directly execute a python command, the result is returned as matrix of
strings:

```
tao.python("lat_ele_list 1@0")
   [[u'0', u'BEGINNING'],
    [u'1', u'BB'],
    [u'2', u'END'],
    [u'3', u'OO']]

tao.python("lat_ele1 1@0>>0|model twiss")
   [[u'beta_a', u'REAL', u'T', u'  4.4000000000000000E+01'],
    [u'alpha_a', u'REAL', u'T', u' -7.0000000000000000E+00'],
    [u'gamma_a', u'REAL', u'F', u'  1.1363636363636365E+00'],
    ...,
    [u'etap_b', u'REAL', u'T', u'  0.0000000000000000E+00']]
```

This only splits the lines and columns of the output into lists, but
there is no parsing of data types. You get the full info returned from
the tao python command.


### `Tao.get_list`

like `Tao.python`, but avoids the extra index column, result is returned as
list of strings:

```
tao.get_list("lat_ele_list 1@0")
   [u'BEGINNING', u'BB', u'END', u'OO']
```

This is often a bit more convenient than `tao.command`, but can be used
only for python commands that return list-like structure.


### `Tao.properties`

like `Tao.python` but more useful for dicts:

```
tao.properties("lat_ele1 1@0>>0|model twiss")
   {'beta_a': 44.0,
    u'alpha_a': -7.0,
    u'gamma_a': 1.1363636363636365,
    ...,
    u'etap_b': 0.0}
```

This adds a lot of convenience, but can also be used just for those
python commands that return dictionary like structures. Note that this
doesn't return the `vary` T/F flag.

(There is also `Tao.parameters` that works similar to `Tao.properties` but
returns a dictionary of `Tao.Parameter` instead - which knows about the
"vary" flag.)

**Comment by rainswor** [comment]
I want to plot the beta function for a lattice using pytao.

Is the standard to procedure to place the beta data in a region e.g. r11, make it visible, extract the curve_data from r11 and finally plot using matplotlib?

It seems like I'm making the plot in tao and then replotting in pytao which seems like I'm doing the same action twice.

**Comment by coldfix** [comment]
Hi,

> Is the standard to procedure to place the beta data in a region e.g. r11, make it visible, extract the curve_data from r11 and finally plot using matplotlib?

Yes, I believe that is the protocol that tao exposes - unless there are any updates on this @DavidSagan?

> It seems like I'm making the plot in tao and then replotting in pytao which seems like I'm doing the same action twice.

Technically, if you disable plots in tao, you're not doing the same action twice here. In this case, moving the plot into the r11 region just tells tao to compute the curve data. You then export this data to python, where you can do arbitrary post-processing, such as plotting. If you're only interested in plotting and don't need a fancy GUI, maybe you don't even need pytao, maybe you're happy with using standalone tao?

I get that this protocol seems a bit confusing, but it's just the way tao is working right now - because it was maybe the simplest way to add external bindings for the existing tao code.

**Comment by coldfix** [comment]
(By the way, can you enclose your code blocks and logs using triple-backtick fences, so they don't lose formatting, see [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Comment by rainswor** [comment]
(sorry, I just cut and paste from the email so I forgot the triple-backtick fences)

Thanks for the info, I just wanted to make sure I understood. I'm also pretty new to tao so I didn't realise that tao doesn't compute the data until I attach it to a region. It's probably not that the protocol is confusing just that I'm trying to learn pytao before I've properly learnt tao.

There's a strong demand for the GUI, I just wanted to have some vague understanding of what was going on behind the scenes before I moved to using the GUI.

**Comment by DavidSagan** [comment]
>>Is the standard to procedure to place the beta data in a region e.g. r11, make it visible, extract the curve_data from r11 and finally plot using matplotlib?

>Yes, I believe that is the protocol that tao exposes - unless there are any updates on this @DavidSagan?

No updates to the protocol. Things were set up like this since it was easy to do. If there is a call for it this can be changed easily enough.

>>It seems like I'm making the plot in tao and then replotting in pytao which seems like I'm doing the same action twice.

No. Tao is calculating the curve points and madqt is plotting them so no duplication.
