### ISSUE TITLE
KeyError: 'DIST_BASE_DIR' when installing

### ISSUE THREAD

**Issue by chrisonian** [hibtc/pytao#2]
On macOS, I have DIST_BASE_DIR defined, and python's os module can read it:
$ls $DIST_BASE_DIR/production
bin     include lib     map     modules share

```
 $python
Python 3.6.1 (default, Jun  2 2017, 11:13:48) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['DIST_BASE_DIR']
'/Users/chrisonian/Code/bmad_svn/'
>>> 
```

But I get this error when installing:

```
$sudo python setup.py install --bmad-dir= $DIST_BASE_DIR/production
Traceback (most recent call last):
  File "setup.py", line 230, in <module>
    main(sys.argv)
  File "setup.py", line 50, in main
    setup_args = get_setup_args(sys.argv)
  File "setup.py", line 91, in get_setup_args
    extension_args = get_extension_args(argv)
  File "setup.py", line 151, in get_extension_args
    base_dir = os.environ['DIST_BASE_DIR']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'DIST_BASE_DIR'
```

**Comment by coldfix** [comment]
The installer assumes you would activate your the bmad distribution before calling it. Otherwise, you have to specify DIST_BASE_DIR and ACC_PLOT_PACKAGE variables manually.

**Comment by chrisonian** [comment]
Hi thomas, it is activated:

```
$. util/dist_source_me 
Using: GNU Fortran (MacPorts gcc5 5.4.0_1) 5.4.0
Checking current working directory...
Current working directory is the root of a distribution tree.
Directory appears to be the top level of a source distribution... GOOD.
$DIST_BASE_DIR = /Users/chrisonian/Code/bmad_svn
$ACC_ROOT_DIR = /Users/chrisonian/Code/bmad_svn
Sourcing build preferences...
Sourcing build variable set...
```

```
$sudo python setup.py install --bmad-dir=/Users/chrisonian/Code/bmad_svn/production
Password:
Traceback (most recent call last):
  File "setup.py", line 230, in <module>
    main(sys.argv)
  File "setup.py", line 50, in main
    setup_args = get_setup_args(sys.argv)
  File "setup.py", line 91, in get_setup_args
    extension_args = get_extension_args(argv)
  File "setup.py", line 151, in get_extension_args
    base_dir = os.environ['DIST_BASE_DIR']
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: ‘DIST_BASE_DIR'
```

**Comment by coldfix** [comment]
use of sudo deactivates most of your environment variables to protect the root environment from malicious state (e.g. PATH modifications and more) carrying over. Also, you don't need sudo. Better install in a virtualenv or as user, i.e. `pip install --user`, maybe even `python setup.py install --user` will work.

**Comment by DavidSagan** [comment]
I suspect that since you are using sudo your environmental variables are not getting setup properly. I have seen this before.

**Comment by coldfix** [comment]
Sorry, I didn't read through your first message. Can you please use code markers to make it more easy to read or all your log messages etc will lose their formatting, see [Creating and highlighting code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/).)

**Comment by chrisonian** [comment]
I fixed it with a prefix:

```
python setup.py install --bmad-dir=/Users/chrisonian/Code/bmad_svn/production --prefix=/Users/chrisonian/Code/python
```

And added this to my .bash_profile:

```
export PYTHONPATH=$PYTHONPATH:/Users/chrisonian/Code/python/lib/python3.6/site-packages/
```

**Comment by coldfix** [comment]
Oh, apparently email replies do not support markdown. Didn't even know that.

**Comment by coldfix** [comment]
IMO, `python setup.py install --user` is much cleaner. And while you're not in production environment you may even want `python setup.py develop --user` to have the module be loaded directly from the files of the repository rather than copying them around.

**Comment by chrisonian** [comment]
Thanks. That works too.
